name: TCS Joining Letter Check

on:
  schedule:
    # Runs at 12:00 PM IST (6:30 AM UTC) and 8:00 PM IST (2:30 PM UTC) every day
    - cron: '30 6,14 * * *'
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.10'
  HEADLESS: 'True'
  SCRIPT_TIMEOUT: '100'

jobs:
  check-joining-letter:
    name: Check TCS Joining Letter
    runs-on: ubuntu-latest
    timeout-minutes: 15
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install Playwright
      uses: microsoft/playwright-github-action@v1
      with:
        install-deps: true
        browsers: chromium
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run TCS Joining Letter Check
      env:
        TCS_EMAIL: ${{ secrets.TCS_EMAIL }}
        GMAIL_EMAIL: ${{ secrets.GMAIL_EMAIL }}
        GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        HEADLESS: ${{ env.HEADLESS }}
        SCRIPT_TIMEOUT: ${{ env.SCRIPT_TIMEOUT }}
      run: |
        python main.py
      
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: logs-${{ github.run_id }}
        path: logs/
        retention-days: 7